### ISSUE TITLE
excel files are missing 

### ISSUE THREAD

**Issue by solwan** [tobystaines/RoadAccidentsPODS#1]
there are some excel files are missing 
trafficVol = pd.read_excel('tra0307.xlsx') # Govt estimates of road use
population = pd.read_excel('pop_est_mid16.xls',index_col=0) # Population figues by Local Authority
refDataDict = pd.read_excel('Road-Accident-Safety-Data-Guide.xls',sheetname=None)

please upload them

**Comment by tobystaines** [comment]
Sorry about that. I've uploaded tra0307.xlsx and pop_est_mid16.xls. You don't need to run the ref data file because the cleaned up versions are already included (but if you really want to, let me know and I can provide the raw data and mapping file as well)
